format = """
$username$hostname$directory$git_branch$git_status$git_state$python$cmd_duration$character
"""
add_newline = false

[directory]
 style = "bold #8A8A8D"
  truncation_length = 3
 truncate_to_repo = true
 format = "[$path]($style) "

[character]
 success_symbol = "[âˆ·](bold #FFC107)"
 error_symbol = "[âˆ·](bold #D35F5F)"
 vimcmd_symbol = "[âˆ·](bold #E68E0D)"

[git_branch]
 symbol = "î‚  "                        # branch symbol
 format = "[$symbol$branch]($style) "
 style = "bold #FFC107"

[git_status]
 format = "([$all_status$ahead_behind]($style)) "
 style = "#FFC107"
 conflicted = "="
 untracked = "?"
 modified = "!"
 staged = "+"
 renamed = "Â»"
 deleted = "âœ˜"
 stashed = "â‰¡"

[git_state]
 format = "[$state( $progress_current/$progress_total)]($style)"
 style = "bold #FFC107"

[cmd_duration]
 min_time = 500
 format = " [$duration]($style) "
 style = "#BEBEBE"

[python]
 symbol = "î˜†  "                          # Python logo glyph
 format = "[$symbol$virtualenv]($style)"
 style = "#E68E0D"

[username]
 style_user = "bold #FFC107"
 style_root = "bold #D35F5F"
 format = "[$user]($style)@"
 disabled = false
 show_always = true

[hostname]
 ssh_only = true
 format = "ðŸ“¡ [$hostname]($style) "
 style = "bold #E68E0D"
 disabled = false
